export const initialResumeData = {
  personalInfo: {
    fullName: '',
    title: '',
    email: '',
    phone: '',
    location: '',
    linkedin: '',
    github: '',
    website: '',
    profilePhoto: '',
  },
  summary: '',
  experience: [],
  education: [],
  skills: [],
  tools: [],
  languages: [],
  certifications: [],
  projects: [],
}
